INSERT INTO libri SET titolo = 'L\'ombra del vento', pagine = 567, prezzo = 15.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Il nome della rosa', pagine = 512, prezzo = 12.5, editore_id = 1;
INSERT INTO libri SET titolo = '1984', pagine = 328, prezzo = 10.9, editore_id = 1;
INSERT INTO libri SET titolo = 'Il piccolo principe', pagine = 96, prezzo = 8.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Orgoglio e pregiudizio', pagine = 352, prezzo = 11.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Harry Potter e la pietra filosofale', pagine = 309, prezzo = 14.5, editore_id = 1;
INSERT INTO libri SET titolo = 'Il grande Gatsby', pagine = 180, prezzo = 9.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Il ritratto di Dorian Gray', pagine = 256, prezzo = 6.9, editore_id = 1;
INSERT INTO libri SET titolo = 'Il signore degli anelli', pagine = 1248, prezzo = 35.0, editore_id = 1;
INSERT INTO libri SET titolo = 'La casa degli spiriti', pagine = 448, prezzo = 13.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Cent\'anni di solitudine', pagine = 432, prezzo = 14.0, editore_id = 1;
INSERT INTO libri SET titolo = 'La solitudine dei numeri primi', pagine = 304, prezzo = 10.5, editore_id = 1;
INSERT INTO libri SET titolo = 'Anna Karenina', pagine = 864, prezzo = 16.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Il cacciatore di aquiloni', pagine = 391, prezzo = 13.49, editore_id = 1;
INSERT INTO libri SET titolo = 'Don Chisciotte della Mancia', pagine = 928, prezzo = 19.9, editore_id = 1;
INSERT INTO libri SET titolo = 'La fattoria degli animali', pagine = 141, prezzo = 8.49, editore_id = 1;
INSERT INTO libri SET titolo = 'Dracula', pagine = 488, prezzo = 7.9, editore_id = 1;
INSERT INTO libri SET titolo = 'Viaggio al centro della Terra', pagine = 284, prezzo = 9.99, editore_id = 1;
INSERT INTO libri SET titolo = 'Moby Dick', pagine = 720, prezzo = 15.5, editore_id = 1;
INSERT INTO libri SET titolo = 'I promessi sposi', pagine = 712, prezzo = 12.99, editore_id = 1;
