
CREATE TABLE games (
    game_id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100), 
    genere VARCHAR(100), 
    publisher VARCHAR(100), 
    platform VARCHAR(100), 
    year INT CHECK (year > 1960)
); 
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Oregon Trail','Strategy','MECC','HP 2100',1971);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Pong','Sports','Atari, Inc.','Arcade',1972);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Combat','Top-down shooter','Atari, Inc.','Atari 2600',1977);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Zork','Adventure','Infocom','PDP-10',1977);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Space Invaders','Shoot \'em up','Taito','Arcade',1978);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Asteroids','Shoot \'em up','Atari, Inc.','Arcade',1979);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Adventure','Action-adventure','Atari, Inc.','Atari 2600',1980);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Battlezone','Vehicle simulation','Atari, Inc.','Arcade',1980);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Missile Command','Shoot \'em up','Atari, Inc.','Arcade',1980);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Pac-Man','Maze','Namco','Arcade',1980);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Centipede','Shoot \'em up','Atari, Inc.','Arcade',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Defender','Shoot \'em up','Williams Entertainment','Arcade',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Donkey Kong','Platform','Nintendo','Arcade',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Frogger','Action','Konami/Sega','Arcade',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Galaga','Shoot \'em up','Namco','Arcade',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tempest','Shoot \'em up','Atari, Inc.','Arcade',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wizardry: Proving Grounds of the Mad Overlord','Role-playing','Sir-Tech','Apple II',1981);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Joust','Action','Williams','Arcade',1982);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ms. Pac-Man','Maze','Midway','Arcade',1982);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Pitfall!','Platform','Activision','Atari 2600',1982);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Robotron: 2084','Top-down shooter','Williams','Arcade',1982);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Archon: The Light and the Dark','Strategy','Electronic Arts','Atari 8-bit family',1983);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Lode Runner','Platform','Broderbund','Apple II',1983);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('M.U.L.E.','Business simulation','Electronic Arts','Atari 8-bit family',1983);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Wars','Shoot \'em up','Atari, Inc.','Arcade',1983);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Elite','Space flight simulator','Acornsoft','BBC Micro',1984);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Marble Madness','Action','Atari Games','Arcade',1984);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tetris','Puzzle','Elorg','Electronika 60',1984);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gauntlet','Action role-playing','Atari Games','Arcade',1985);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ghosts \'n Goblins','Platform','Capcom','Arcade',1985);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario Bros.','Platform','Nintendo','NES',1985);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ultima IV: Quest of the Avatar','Role-playing','Origin Systems','Apple II',1985);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Arkanoid','Block breaker','Taito','Arcade',1986);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Bubble Bobble','Platform','Taito','Arcade',1986);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda','Action-adventure','Nintendo','NES',1986);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Out Run','Racing','Sega','Arcade',1986);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Contra','Run and gun','Konami','Arcade',1987);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Double Dragon','Beat \'em up','Technos Japan','Arcade',1987);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dungeon Master','Role-playing','FTL Games','Atari ST',1987);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mike Tyson\'s Punch-Out!!','Sports','Nintendo','NES',1987);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('R-Type','Shoot \'em up','Irem','Arcade',1987);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sid Meier\'s Pirates!','Action-adventure','MicroProse','Commodore 64',1987);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mega Man 2','Platform','Capcom','NES',1988);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ninja Gaiden','Platform','Tecmo','NES',1988);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario Bros. 3','Platform','Nintendo','NES',1988);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Final Fight','Beat \'em up','Capcom','Arcade',1989);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Populous','God game','Electronic Arts','Amiga',1989);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Prince of Persia','Platform','Broderbund','Apple II',1989);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('SimCity','City-building','Maxis','Amiga, Macintosh',1989);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Secret of Monkey Island','Adventure','LucasArts','PC',1990);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Speedball 2: Brutal Deluxe','Sports','Image Works','Atari ST',1990);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario World','Platform','Nintendo','Super NES',1990);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wing Commander','Space flight simulator','Origin Systems','PC',1990);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Another World','Platform','Delphine Software','Amiga, Atari ST',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Civilization','Turn-based strategy','MicroProse','PC',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Final Fantasy IV','Role-playing','Square','Super NES',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: A Link to the Past','Action-adventure','Nintendo','Super NES',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Lemmings','Puzzle','Psygnosis','Amiga',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Micro Machines','Racing','Camerica','NES',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Monkey Island 2: LeChuck\'s Revenge','Adventure','LucasArts','PC',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sonic the Hedgehog','Platform','Sega','Sega Genesis',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Street Fighter II','Fighting','Capcom','Arcade',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Castlevania IV','Platform','Konami','Super NES',1991);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Alone in the Dark','Survival horror','Infogrames','PC',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Contra III: The Alien Wars','Run and gun','Konami','Super NES',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dune II','Real-time strategy','Virgin Games','PC',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Flashback','Platform','U.S. Gold','Amiga',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Indiana Jones and the Fate of Atlantis','Adventure','LucasArts','PC',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mortal Kombat','Fighting','Midway','Arcade',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sensible Soccer','Sports','Renegade Software','Amiga, Atari ST',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sonic the Hedgehog 2','Platform','Sega','Sega Genesis',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Control II','Action-adventure','Accolade','PC',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Streets of Rage 2','Beat \'em up','Sega','Sega Genesis',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario Kart','Kart racing','Nintendo','Super NES',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ultima VII: The Black Gate','Role-playing','Origin Systems','PC',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Virtua Racing','Racing','Sega','Arcade',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wolfenstein 3D','First-person shooter','Apogee Software','PC',1992);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Day of the Tentacle','Adventure','LucasArts','PC',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Daytona USA','Racing','Sega','Arcade',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Doom','First-person shooter','id Software','PC',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gunstar Heroes','Run and gun','Sega','Sega Genesis',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: Link\'s Awakening','Action-adventure','Nintendo','Game Boy',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mega Man X','Platform','Capcom','Super NES',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mortal Kombat II','Fighting','Midway','Arcade',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Myst','Adventure','Broderbund','Macintosh',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('NBA Jam','Sports','Midway','Arcade',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Phantasy Star IV','Role-playing','Sega','Sega Genesis',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ridge Racer','Racing','Namco','Arcade',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sam & Max Hit the Road','Adventure','LucasArts','PC',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Secret of Mana','Action role-playing','Square','Super NES',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Samurai Shodown','Fighting','SNK','Arcade',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('SimCity 2000','City-building','Maxis','Macintosh',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Fox','Shoot \'em up','Nintendo','Super NES',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Syndicate','Real-time tactics','Electronic Arts','Amiga, PC',1993);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Donkey Kong Country','Platform','Nintendo','Super NES',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Doom II','First-person shooter','GT Interactive','PC',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('EarthBound','Role-playing','Nintendo','Super NES',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Final Fantasy VI','Role-playing','Square','Super NES',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sega Rally Championship','Racing','Sega','Arcade',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Sensible World of Soccer','Sports','Renegade Software','Amiga',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Wars: TIE Fighter','Space flight simulator','LucasArts','PC',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Metroid','Action-adventure','Nintendo','Super NES',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tempest 2000','Shoot \'em up','Atari Corporation','Atari Jaguar',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Theme Park','Business simulation','Electronic Arts','Amiga, PC',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Virtua Fighter 2','Fighting','Sega','Arcade',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('X-COM: UFO Defense','Turn-based strategy','MicroProse','PC',1994);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Chrono Trigger','Role-playing','Square','Super NES',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Command & Conquer','Real-time strategy','Virgin Interactive','PC',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('MechWarrior 2: 31st Century Combat','Vehicle simulation','Activision','PC',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Warcraft II: Tides of Darkness','Real-time strategy','Blizzard Entertainment','PC',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wipeout','Racing','Psygnosis','PC, PlayStation',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Worms','Artillery','Ocean Software','Amiga',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Yoshi\'s Island','Platform','Nintendo','Super NES',1995);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Civilization II','Turn-based strategy','MicroProse','PC',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Command & Conquer: Red Alert','Real-time strategy','Virgin Interactive','PC',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Duke Nukem 3D','First-person shooter','GT Interactive','PC',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mario Kart 64','Kart racing','Nintendo','Nintendo 64',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Nights into Dreams...','Action','Sega','Saturn',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('PaRappa the Rapper','Rhythm','Sony Computer Entertainment','PlayStation',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Pokémon Redand Blue','Role-playing','Nintendo','Game Boy',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Quake','First-person shooter','GT Interactive','PC',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Resident Evil','Survival horror','Capcom','PlayStation',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario 64','Platform','Nintendo','Nintendo 64',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tekken 3','Fighting','Namco','Arcade',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tomb Raider','Action-adventure','Eidos Interactive','Saturn, PC, PlayStation',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wave Race 64','Racing','Nintendo','Nintendo 64',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wipeout 2097','Racing','Psygnosis','PlayStation',1996);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Age of Empires','Real-time strategy','Microsoft','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Castlevania: Symphony of the Night','Action-adventure','Konami','PlayStation',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Diablo','Action role-playing','Blizzard Entertainment','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Fallout','Role-playing','Interplay Entertainment','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Final Fantasy Tactics','Tactical role-playing','Square','PlayStation',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Final Fantasy VII','Role-playing','Square','PlayStation',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('GoldenEye 007','First-person shooter','Nintendo','Nintendo 64',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gran Turismo','Racing','Sony Computer Entertainment','PlayStation',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grand Theft Auto','Action-adventure','BMG Interactive','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Quake II','First-person shooter','Activision','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Fox 64','Shoot \'em up','Nintendo','Nintendo 64',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Wars Jedi Knight: Dark Forces II','First-person shooter','LucasArts','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Total Annihilation','Real-time strategy','Cavedog Entertainment','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ultima Online','MMORPG','Electronic Arts','PC',1997);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Baldur\'s Gate','Role-playing','Black Isle Studios','PC',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Crash Bandicoot: Warped','Platform','Sony Computer Entertainment','PlayStation',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dance Dance Revolution','Rhythm','Konami','Arcade',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Fallout 2','Role-playing','Interplay Entertainment','PC',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grim Fandango','Adventure','LucasArts','PC',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Half-Life','First-person shooter','Sierra Studios','PC',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: Ocarina of Time','Action-adventure','Nintendo','Nintendo 64',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Metal Gear Solid','Stealth','Konami','PlayStation',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Panzer Dragoon Saga','Role-playing','Sega','Saturn',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Resident Evil 2','Survival horror','Capcom','PlayStation',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Soulcalibur','Fighting','Namco','Arcade',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('StarCraft','Real-time strategy','Blizzard Entertainment','PC',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Suikoden II','Role-playing','Konami','PlayStation',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Thief: The Dark Project','Stealth','Eidos Interactive','PC',1998);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Age of Empires II','Real-time strategy','Microsoft','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('EverQuest','MMORPG','Sony Online Entertainment','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Homeworld','Real-time strategy','Sierra Studios','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Planescape: Torment','Role-playing','Interplay Entertainment','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Pokémon Goldand Silver','Role-playing','Nintendo','Game Boy Color',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Quake III: Arena','First-person shooter','Activision','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Shenmue','Adventure','Sega','Dreamcast',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Silent Hill','Survival horror','Konami','PlayStation',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('System Shock 2','First-person shooter','Electronic Arts','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Unreal Tournament','First-person shooter','GT Interactive','PC',1999);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Baldur\'s Gate II: Shadows of Amn','Role-playing','Black Isle Studios','PC',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Counter-Strike','First-person shooter','Valve','PC',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Deus Ex','Action role-playing','Eidos Interactive','PC',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Diablo II','Action role-playing','Blizzard Entertainment','PC',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Jet Set Radio','Platform','Sega','Dreamcast',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: Majora\'s Mask','Action-adventure','Nintendo','Nintendo 64',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Marvel vs. Capcom 2: New Age of Heroes','Fighting','Capcom','Arcade',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Sims','Life simulation','Electronic Arts','PC',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Thief II: The Metal Age','Stealth','Eidos Interactive','PC',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tony Hawk\'s Pro Skater 2','Sports','Activision','PlayStation',2000);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Advance Wars','Turn-based tactics','Nintendo','Game Boy Advance',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Animal Crossing','Life simulation','Nintendo','GameCube',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Devil May Cry','Action-adventure','Capcom','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Final Fantasy X','Role-playing','Square','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gran Turismo 3: A-Spec','Racing','Sony Computer Entertainment','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grand Theft Auto III','Action-adventure','Rockstar Games','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Halo: Combat Evolved','First-person shooter','Microsoft Game Studios','Xbox',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ico','Action-adventure','Sony Computer Entertainment','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ikaruga','Shoot \'em up','Treasure','Arcade',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Max Payne','Third-person shooter','Gathering of Developers','PC',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Metal Gear Solid 2: Sons of Liberty','Stealth','Konami','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Phoenix Wright: Ace Attorney','Adventure','Capcom','Game Boy Advance',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Rez','Shoot \'em up','Sega','Dreamcast, PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Silent Hill 2','Survival horror','Konami','PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Smash Bros. Melee','Fighting','Nintendo','GameCube',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tony Hawk\'s Pro Skater 3','Sports','Activision','PlayStation, PlayStation 2',2001);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Battlefield 1942','First-person shooter','Electronic Arts','PC',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Elder Scrolls III: Morrowind','Action role-playing','Bethesda Softworks','PC',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Eternal Darkness: Sanity\'s Requiem','Survival horror','Nintendo','GameCube',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grand Theft Auto: Vice City','Action-adventure','Rockstar Games','PlayStation 2',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Kingdom Hearts','Action role-playing','Square','PlayStation 2',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: The Wind Waker','Action-adventure','Nintendo','GameCube',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Metroid Prime','Action-adventure','Nintendo','GameCube',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Soulcalibur II','Fighting','Namco','Arcade',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tom Clancy\'s Splinter Cell','Stealth','Ubisoft','Xbox',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Warcraft III: Reign of Chaos','Real-time strategy','Blizzard Entertainment','PC, Macintosh',2002);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Beyond Good & Evil','Action-adventure','Ubisoft','PlayStation 2',2003);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('F-Zero GX','Racing','Nintendo','GameCube',2003);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Max Payne 2: The Fall of Max Payne','Third-person shooter','Rockstar Games','PC',2003);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Prince of Persia: The Sands of Time','Action-adventure','Ubisoft','PlayStation 2',2003);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Star Wars: Knights of the Old Republic','Role-playing','LucasArts','Xbox',2003);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('WarioWare, Inc.: Mega Microgames!','Action','Nintendo','Game Boy Advance',2003);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Burnout 3: Takedown','Racing','Electronic Arts','PlayStation 2, Xbox',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Chronicles of Riddick: Escape from Butcher Bay','Stealth','Vivendi Universal Games','Xbox',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dragon Quest VIII','Role-playing','Square Enix','PlayStation 2',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gran Turismo 4','Racing','Sony Computer Entertainment','PlayStation 2',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grand Theft Auto: San Andreas','Action-adventure','Rockstar Games','PlayStation 2',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Half-Life 2','First-person shooter','Valve','PC',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Halo 2','First-person shooter','Microsoft Game Studios','Xbox',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Katamari Damacy','Action','Namco','PlayStation 2',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Metal Gear Solid 3: Snake Eater','Stealth','Konami','PlayStation 2',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Rome: Total War','Strategy','Activision','PC',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Sims 2','Life simulation','Electronic Arts','PC',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('World of Warcraft','MMORPG','Blizzard Entertainment','PC, Macintosh',2004);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Call of Duty 2','First-person shooter','Activision','PC',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Civilization IV','Turn-based strategy','2K Games','PC',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Devil May Cry 3: Dante\'s Awakening','Action-adventure','Capcom','PlayStation 2',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('God of War','Action-adventure','Sony Computer Entertainment','PlayStation 2',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Guitar Hero','Rhythm','RedOctane','PlayStation 2',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Psychonauts','Platform','Majesco','PC, Xbox',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Resident Evil 4','Survival horror','Capcom','GameCube',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Shadow of the Colossus','Action-adventure','Sony Computer Entertainment','PlayStation 2',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Tom Clancy\'s Splinter Cell: Chaos Theory','Stealth','Ubisoft','GameCube, PC, PlayStation 2, Xbox',2005);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Company of Heroes','Real-time strategy','THQ','PC',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Elder Scrolls IV: Oblivion','Action role-playing','2K Games, Bethesda Softworks','PC, Xbox 360',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gears of War','Third-person shooter','Microsoft Game Studios','Xbox 360',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Hitman: Blood Money','Stealth','Eidos Interactive','PC, PlayStation 2, Xbox, Xbox 360',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: Twilight Princess','Action-adventure','Nintendo','GameCube, Wii',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Ōkami','Action-adventure','Capcom','PlayStation 2',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Wii Sports','Sports','Nintendo','Wii',2006);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('BioShock','First-person shooter','2K Games','PC, Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Call of Duty 4: Modern Warfare','First-person shooter','Activision','PC, PlayStation 3, Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('God of War II','Action-adventure','Sony Computer Entertainment','PlayStation 2',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Halo 3','First-person shooter','Microsoft Game Studios','Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mass Effect','Action role-playing','Microsoft Game Studios','Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Portal','Puzzle-platformer','Valve','PC, Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Rock Band','Rhythm','MTV Games','PlayStation 3, Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario Galaxy','Platform','Nintendo','Wii',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Team Fortress 2','First-person shooter','Valve','PC, Xbox 360',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The World Ends with You','Role-playing','Square Enix','Nintendo DS',2007);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Braid','Puzzle-platformer','Microsoft Game Studios','Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Burnout Paradise','Racing','Electronic Arts','PC, PlayStation 3, Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dead Space','Survival horror','Electronic Arts','PlayStation 3, Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Fable II','Action role-playing','Microsoft Game Studios','Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Fallout 3','Action role-playing','Bethesda Softworks','PC, PlayStation 3, Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Gears of War 2','Third-person shooter','Microsoft Game Studios','Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grand Theft Auto IV','Action-adventure','Rockstar Games','PlayStation 3, Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Left 4 Dead','First-person shooter','Valve','PC, Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('LittleBigPlanet','Platform','Sony Computer Entertainment','PlayStation 3',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Persona 4','Role-playing','Atlus','PlayStation 2',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Rock Band 2','Rhythm','MTV Games','Xbox 360',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Spelunky','Platform','Derek Yu','PC',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Street Fighter IV','Fighting','Capcom','Arcade',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Valkyria Chronicles','Tactical role-playing','Sega','PlayStation 3',2008);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Angry Birds','Puzzle','Rovio Entertainment','Maemo, iOS',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Assassin\'s Creed II','Action-adventure','Ubisoft','PlayStation 3, Xbox 360',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Batman: Arkham Asylum','Action-adventure','Eidos Interactive, Warner Bros. Interactive Entertainment','PlayStation 3, Xbox 360',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Bayonetta','Action','Sega','PlayStation 3, Xbox 360',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Borderlands','Action role-playing','2K Games','PC, PlayStation 3, Xbox 360',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Demon\'s Souls','Action role-playing','Sony Computer Entertainment','PlayStation 3',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dragon Age: Origins','Role-playing','Electronic Arts','PC, PlayStation 3, Xbox 360',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('League of Legends','MOBA','Riot Games','PC',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Left 4 Dead 2','First-person shooter','Valve','PC, Xbox 360',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Plants vs. Zombies','Tower defense','PopCap Games','PC, Macintosh',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Uncharted 2: Among Thieves','Action-adventure','Sony Computer Entertainment','PlayStation 3',2009);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('God of War III','Action-adventure','Sony Computer Entertainment','PlayStation 3',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Heavy Rain','Adventure','Sony Computer Entertainment','PlayStation 3',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Limbo','Platform','Microsoft Game Studios','Xbox 360',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Mass Effect 2','Action role-playing','Electronic Arts','PC, Xbox 360',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Red Dead Redemption','Action-adventure','Rockstar Games','PlayStation 3, Xbox 360',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Rock Band 3','Rhythm','MTV Games','Nintendo DS, PlayStation 3, Xbox 360, Wii',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('StarCraft II: Wings of Liberty','Real-time strategy','Blizzard Entertainment','PC, Macintosh',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario Galaxy 2','Platform','Nintendo','Wii',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Meat Boy','Platform','Team Meat','Xbox 360',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Xenoblade Chronicles','Action role-playing','Nintendo','Wii',2010);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Batman: Arkham City','Action-adventure','Warner Bros. Interactive Entertainment','PlayStation 3, Xbox 360',2011);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dark Souls','Action role-playing','Namco Bandai Games','PlayStation 3, Xbox 360',2011);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Elder Scrolls V: Skyrim','Action role-playing','Bethesda Softworks','PC, PlayStation 3, Xbox 360',2011);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Minecraft','Sandbox','Mojang','PC',2011);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Portal 2','Puzzle-platformer','Valve','PC, PlayStation 3, Xbox 360',2011);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dishonored','Stealth','Bethesda Softworks','PC, PlayStation 3, Xbox 360',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Far Cry 3','First-person shooter','Ubisoft','PC, PlayStation 3, Xbox 360',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Fire Emblem: Awakening','Tactical role-playing','Nintendo','Nintendo 3DS',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Journey','Adventure','Sony Computer Entertainment','PlayStation 3',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Hotline Miami','Action','Devolver Digital','PC',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Walking Dead','Adventure','Telltale Games','PC, PlayStation 3, Xbox 360',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('XCOM: Enemy Unknown','Turn-based strategy','2K Games','PC, PlayStation 3, Xbox 360',2012);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('BioShock Infinite','First-person shooter','2K Games','PC, PlayStation 3, Xbox 360',2013);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Dota 2','MOBA','Valve','PC',2013);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Grand Theft Auto V','Action-adventure','Rockstar Games','PlayStation 3, Xbox 360',2013);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Last of Us','Action-adventure','Sony Computer Entertainment','PlayStation 3',2013);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Papers, Please','Puzzle','3909 LLC','PC, Macintosh',2013);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Destiny','First-person shooter','Bungie','PlayStation 3, PlayStation 4, Xbox 360, Xbox One',2014);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Shovel Knight','Platform','Yacht Club Games','Nintendo 3DS, PC, Wii U',2014);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Bloodborne','Action role-playing','Sony Computer Entertainment','PlayStation 4',2015);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Rocket League','Sports','Psyonix','PC, PlayStation 4',2015);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Undertale','Role-playing','Toby Fox','PC, Macintosh',2015);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Witcher 3: Wild Hunt','Action role-playing','CD Projekt','PC, PlayStation 4, Xbox One',2015);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Inside','Platform','Playdead','Xbox One',2016);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Overwatch','First-person shooter','Blizzard Entertainment','PC, PlayStation 4, Xbox One',2016);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Stardew Valley','Simulation','ConcernedApe','PC',2016);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Uncharted 4: A Thief\'s End','Action-adventure','Sony Computer Entertainment','PlayStation 4',2016);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('The Legend of Zelda: Breath of the Wild','Action-adventure','Nintendo','Nintendo Switch, Wii U',2017);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Super Mario Odyssey','Platform','Nintendo','Nintendo Switch',2017);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('God of War','Action-adventure','Sony Interactive Entertainment','PlayStation 4',2018);
INSERT INTO games (nome, genere, publisher, platform, `year`) VALUES ('Red Dead Redemption 2','Action-adventure','Rockstar Games','PlayStation 4, Xbox One',2018);
